workflows:
  ios-workflow:
    name: iOS Build
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor
        script: ./node_modules/.bin/cap sync ios
      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release -allowProvisioningUpdates archive -archivePath $CM_BUILD_DIR/build.xcarchive CODE_SIGN_IDENTITY="iPhone Developer"
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/build
    artifacts:
      - build/*.ipa
