stages:
  - build
  - deploy

ios_build:
  stage: build
  image: macos:latest
  before_script:
    - brew install node
    - npm install -g @bubblewrap/cli  # Wait, for iOS it's different
    # Actually, for iOS, since using PWABuilder, perhaps need to download the project
    # This is tricky. Assuming we have the Xcode project in repo or generate it.
    # For simplicity, assuming the Xcode project is in the repo under ios/
  script:
    - cd ios
    - xcodebuild -workspace MyBudget.xcworkspace -scheme MyBudget -sdk iphoneos -configuration Release archive -archivePath $CI_PROJECT_DIR/build.xcarchive
    - xcodebuild -exportArchive -archivePath $CI_PROJECT_DIR/build.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CI_PROJECT_DIR/build
  artifacts:
    paths:
      - build/MyBudget.ipa
    expire_in: 1 week
  only:
    - main
    - tags

ios_deploy:
  stage: deploy
  image: ruby:3.0
  dependencies:
    - ios_build
  before_script:
    - gem install fastlane
    - echo "$APPLE_CERTIFICATE" | base64 -d > certificate.p12
    - echo "$APPLE_PROVISIONING_PROFILE" | base64 -d > profile.mobileprovision
  script:
    - fastlane ios deploy
  environment:
    name: production
  only:
    - tags
  when: manual