stages:
  - build
  - deploy

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.0"
  ANDROID_SDK_TOOLS: "9477386"

android_build:
  stage: build
  image: openjdk:11-jdk
  before_script:
    - apt-get update -qq && apt-get install -y -qq curl unzip
    - curl -s https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip -o android-sdk.zip
    - unzip -q android-sdk.zip -d android-sdk
    - export ANDROID_HOME=$PWD/android-sdk
    - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
    - yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    - $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}"
    - npm install -g @bubblewrap/cli
  script:
    - bubblewrap build
  artifacts:
    paths:
      - app-release-signed.apk
      - app-release-bundle.aab
    expire_in: 1 week
  only:
    - main
    - tags

android_deploy:
  stage: deploy
  image: ruby:3.0
  dependencies:
    - android_build
  before_script:
    - gem install fastlane
    - echo "$ANDROID_KEYSTORE" | base64 -d > android.keystore
  script:
    - fastlane android deploy
  environment:
    name: production
  only:
    - tags
  when: manual