# Fastfile for Android and iOS deployment

platform :android do
  desc "Deploy Android APK to Google Play Store"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      apk: '../app-release-signed.apk',
      json_key_data: ENV['GOOGLE_PLAY_JSON_KEY'],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end

platform :ios do
  desc "Deploy iOS IPA to App Store"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      key_content: ENV['APP_STORE_PRIVATE_KEY']
    )
    upload_to_app_store(
      api_key: api_key,
      ipa: 'build/MyBudget.ipa',
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end